import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1746859688740 implements MigrationInterface {
    name = 'Migrations1746859688740'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "posts_uid_fkey"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "posts_main_category_fkey"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_uid_fkey"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_following_uid_fkey"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP CONSTRAINT "follow_requests_uid_fkey"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP CONSTRAINT "follow_requests_following_uid_fkey"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "post_subcategories_post_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "post_subcategories_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_post_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_uid_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."users_username_idx"`);
        await queryRunner.query(`DROP INDEX "public"."posts_uid_idx"`);
        await queryRunner.query(`DROP INDEX "public"."follows_uid_following_uid_idx"`);
        await queryRunner.query(`DROP INDEX "public"."follow_requests_uid_following_uid_idx"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP CONSTRAINT "sub_categories_pkey"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP CONSTRAINT "sub_categories_category_name_key"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP COLUMN "category_name"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "self_intro"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_image_url"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "country_code"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "main_category"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "post_text"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "photo_url"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "public_type_no"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "main_categories" DROP CONSTRAINT "main_categories_pkey"`);
        await queryRunner.query(`ALTER TABLE "main_categories" DROP COLUMN "category_name"`);
        await queryRunner.query(`ALTER TABLE "main_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_pkey"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("uid")`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "following_uid"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP CONSTRAINT "follow_requests_pkey"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "request_id"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "following_uid"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "post_subcategories_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "post_subcategories_pkey" PRIMARY KEY ("category_no")`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "post_subcategories_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP COLUMN "category_no"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_pkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("uid")`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD "categoryId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD CONSTRAINT "PK_dfa3adf1b46e582626b295d0257" PRIMARY KEY ("categoryId")`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD "categoryName" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD CONSTRAINT "UQ_e944616f4c5b1a0b02f760231ba" UNIQUE ("categoryName")`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "userCode" character(6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_e568829997a1d09d009346bc47d" UNIQUE ("userCode")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "selfIntro" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profileImageUrl" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "countryCode" character(2)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "PK_cdc670193be6ca43f590dbabcee" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "mainCategory" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "postText" text`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "photoUrl" text`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "publicTypeNo" character(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "main_categories" ADD "categoryName" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "main_categories" ADD CONSTRAINT "PK_d1c496bd6182320f210356922bf" PRIMARY KEY ("categoryName")`);
        await queryRunner.query(`ALTER TABLE "main_categories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followingUid" character(28) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_pkey"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("uid", "followingUid")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD CONSTRAINT "PK_1cb3940489a0406c7cee29d712d" PRIMARY KEY ("requestId")`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "followingUid" character(28) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "PK_dc17b59c17c8e30cf0ed0b58ec3" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD "categoryNo" character(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "PK_dc17b59c17c8e30cf0ed0b58ec3"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "PK_2cd9053b2486c060dd14c5c37fb" PRIMARY KEY ("postId", "categoryNo")`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD "categoryId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_pkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("uid", "postId")`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_pkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "PK_b097e6b56a0634e988638f85a62" PRIMARY KEY ("postId")`);
        await queryRunner.query(`CREATE INDEX "idx_username" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a27fcb76d4d9efa07bed707f6" ON "posts" ("uid") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecfa66b31f5b492b766414243e" ON "follows" ("uid", "followingUid") `);
        await queryRunner.query(`CREATE INDEX "IDX_51a1244f937b350ece4d053b2f" ON "follow_requests" ("uid", "followingUid") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_51a1244f937b350ece4d053b2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecfa66b31f5b492b766414243e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a27fcb76d4d9efa07bed707f6"`);
        await queryRunner.query(`DROP INDEX "public"."idx_username"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "PK_b097e6b56a0634e988638f85a62"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("uid", "postId")`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_pkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("uid")`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "PK_2cd9053b2486c060dd14c5c37fb"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "PK_dc17b59c17c8e30cf0ed0b58ec3" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP COLUMN "categoryNo"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "PK_dc17b59c17c8e30cf0ed0b58ec3"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "followingUid"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP CONSTRAINT "PK_1cb3940489a0406c7cee29d712d"`);
        await queryRunner.query(`ALTER TABLE "follow_requests" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_pkey"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("uid")`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followingUid"`);
        await queryRunner.query(`ALTER TABLE "main_categories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "main_categories" DROP CONSTRAINT "PK_d1c496bd6182320f210356922bf"`);
        await queryRunner.query(`ALTER TABLE "main_categories" DROP COLUMN "categoryName"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "publicTypeNo"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "photoUrl"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "postText"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "mainCategory"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "PK_cdc670193be6ca43f590dbabcee"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "countryCode"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profileImageUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "selfIntro"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_e568829997a1d09d009346bc47d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "userCode"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP CONSTRAINT "UQ_e944616f4c5b1a0b02f760231ba"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP COLUMN "categoryName"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP CONSTRAINT "PK_dfa3adf1b46e582626b295d0257"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_pkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("post_id", "uid")`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD "category_no" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "post_subcategories_pkey" PRIMARY KEY ("category_no")`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" DROP CONSTRAINT "post_subcategories_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "post_subcategories_pkey" PRIMARY KEY ("post_id", "category_no")`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "following_uid" character(28) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD "request_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD CONSTRAINT "follow_requests_pkey" PRIMARY KEY ("request_id")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "following_uid" character(28) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_pkey"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("uid", "following_uid")`);
        await queryRunner.query(`ALTER TABLE "main_categories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "main_categories" ADD "category_name" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "main_categories" ADD CONSTRAINT "main_categories_pkey" PRIMARY KEY ("category_name")`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "public_type_no" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "photo_url" text`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "post_text" text`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "main_category" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("post_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "country_code" character(2)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_image_url" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "self_intro" text`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD "category_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD CONSTRAINT "sub_categories_category_name_key" UNIQUE ("category_name")`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD CONSTRAINT "sub_categories_pkey" PRIMARY KEY ("category_id")`);
        await queryRunner.query(`CREATE INDEX "follow_requests_uid_following_uid_idx" ON "follow_requests" ("uid", "following_uid") `);
        await queryRunner.query(`CREATE INDEX "follows_uid_following_uid_idx" ON "follows" ("uid", "following_uid") `);
        await queryRunner.query(`CREATE INDEX "posts_uid_idx" ON "posts" ("uid") `);
        await queryRunner.query(`CREATE INDEX "users_username_idx" ON "users" ("username") `);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_uid_fkey" FOREIGN KEY ("uid") REFERENCES "users"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("post_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "post_subcategories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "sub_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_subcategories" ADD CONSTRAINT "post_subcategories_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("post_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD CONSTRAINT "follow_requests_following_uid_fkey" FOREIGN KEY ("following_uid") REFERENCES "users"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follow_requests" ADD CONSTRAINT "follow_requests_uid_fkey" FOREIGN KEY ("uid") REFERENCES "users"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_following_uid_fkey" FOREIGN KEY ("following_uid") REFERENCES "users"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_uid_fkey" FOREIGN KEY ("uid") REFERENCES "users"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "posts_main_category_fkey" FOREIGN KEY ("main_category") REFERENCES "main_categories"("category_name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "posts_uid_fkey" FOREIGN KEY ("uid") REFERENCES "users"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
