version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: test-db
    ports:
      - '${DATASOURCE_PORT}:5432'
    environment:
      POSTGRES_DB: ${DATASOURCE_DATABASE}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data
