name: Feature-To-Dev-CI

on:
  pull_request:
    branches:
      - dev
    paths: ['src/**/*.ts', 'test/**/*.ts', 'tsconfig.json']
  push:
    branches:
      - dev
    paths: ['src/**/*.ts', 'test/**/*.ts', 'tsconfig.json']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run test:cov

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run pretest:e2e && npm run test:e2e
      - if: always()
        run: npm run posttest:e2e
